---
- name: Stop and remove container if it exists
  become: yes
  docker_container:
    name: "{{ container_name }}"
    state: absent

- name: Remove image if it exists
  become: yes
  docker_image:
    name: "{{ image_name }}"
    state: absent

- name: Pull the Docker image
  become: yes
  docker_image:
    name: "{{ image_name }}"
    tag: "{{ image_tag }}"
    source: pull
    
- name: Run the Docker container
  become: yes
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}:{{ image_tag }}"
    state: started
    detach: true
    network_mode: host
    env:
      MASTODON_ACCESS_TOKEN_SOCIAL: "{{ token_social }}"
      MASTODON_ACCESS_TOKEN_AU: "{{ token_au }}"
      MASTODON_ACCESS_TOKEN_CLOUD: "{{ token_cloud }}"
      MASTODON_ACCESS_TOKEN_WORLD: "{{ token_world }}"
      MASTODON_ACCESS_TOKEN_UK: "{{ token_uk }}"
      DB_URL: "{{ db_url }}"
      DB_USERNAME: "{{ db_username }}"
      DB_PASSWORD: "{{ db_password }}"