---
- hosts: harvestor-master
  vars_files:
    - host_vars/harvestor.yaml
  gather_facts: true
  roles:
    - role: install-python-dependency
    - role: install-docker
    - role: create-docker-swarm