---
- hosts: harvestor-worker
  vars_files:
    - host_vars/harvestor.yaml
  gather_facts: true
  roles:
    - role: install-python-dependency
    - role: install-docker
    - role: join-harvestor-swarm